repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.1.1
  hooks:
  - id: check-added-large-files
    args: ["--maxkb=4096"]
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: flake8
    language_version: python3.8
    exclude: ^asr_evaluation/speech_pb2/
    args: ["--max-line-length=100"]
  - id: trailing-whitespace
    files: \.(js|rb|md|py|sh|txt|yaml|yml|kidm)$

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950
  hooks:
  - id: mypy
    language_version: python3.8
    args: [
        --ignore-missing-imports, --disallow-incomplete-defs,
        --warn-unused-ignores,  --warn-redundant-casts,
        --warn-unreachable, --check-untyped-defs
    ]
